import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.scss";
import BootstrapClient from './components/BootstrapClient';
import Script from "next/script"
import { MdOutlinePhone } from "react-icons/md";
import { SlSocialFacebook } from "react-icons/sl";
import { CiTwitter } from "react-icons/ci";
import { FaInstagram } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bonero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Urbanist:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <nav className="bonero-navbar navbar navbar-expand-lg">
          <div className="container">
            <a className="navbar-brand" href="#">
              <img className="bonero1" src="/main/bonero.svg"></img>
              <img className="bonero2" src="/main/bonero_original.svg"></img>
            </a>
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon" />
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                <li className="nav-item">
                  <a className="nav-link active" aria-current="page" href="/">
                    Ana Sayfa
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/hakkimizda">
                    Hakkımızda
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/ozellikler">
                    Özellikler
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/nasil_calisir">
                    Nasıl Çalışır
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/iletisim">
                    İletişim
                  </a>
                </li>
              </ul>
              <a className="nav-link nav-contact" href="#">
                <MdOutlinePhone /> +90 850 322 12 12
              </a>
              <form className="d-flex" role="search">
                <button className="btn demo-button blur" type="submit">
                  Ücretsiz Demo İste
                </button>
              </form>
            </div>
          </div>
        </nav>      
        {children}
        <footer className="footer">
          <div className="footer-container">
            <div className="row">
              <div className="col-lg-3 col-md-6">
                <div className="footer-section about">
                  <h2 className="logo"><img src="/main/bonero_white.svg"></img></h2>
                  <p>
                    Bonero, toplulukların yönetimini kolaylaştırmak için geliştirilmiş kapsamlı bir yazılım platformudur. Misyonumuz, toplulukların büyümesine ve üyelerine daha iyi hizmet vermesine yardımcı olmaktır.
                  </p>
                  <div className="d-flex gap-3 my-4">
                    <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                      <SlSocialFacebook />
                    </a>
                    <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                      <CiTwitter />
                    </a>
                    <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                      <FaInstagram />
                    </a>
                    <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                      <FaLinkedinIn />
                    </a>
                  </div>
                </div>
              </div>
              
              <div className="col-lg-3 col-md-6">
                <div className="footer-section links">
                  <h3 className="mb-4">Hızlı Bağlantılar</h3>
                  <ul>
                    <li><a href="#">Ana Sayfa</a></li>
                    <li><a href="#">Hakkımızda</a></li>
                    <li><a href="#">Özellikler</a></li>
                    <li><a href="#">Referanslar</a></li>
                    <li><a href="#">Fiyatlandırma</a></li>
                    <li><a href="#">İletişim</a></li>
                  </ul>
                </div>
              </div>
              
              <div className="col-lg-3 col-md-6">
                <div className="footer-section links">
                  <h3 className="mb-4">Çözümlerimiz</h3>
                  <ul>
                    <li><a href="#">Üye Yönetimi</a></li>
                    <li><a href="#">Etkinlik Yönetimi</a></li>
                    <li><a href="#">Aidat Takibi</a></li>
                    <li><a href="#">İletişim Araçları</a></li>
                    <li><a href="#">Mobil Uygulama</a></li>
                    <li><a href="#">Analitik ve Raporlama</a></li>
                  </ul>
                </div>
              </div>
              
              <div className="col-lg-3 col-md-6">
                <div className="footer-section subscribe">
                  <h3 className="mb-4">Bültenimize Abone Olun</h3>
                  <p>
                    Topluluk yönetimi ile ilgili güncel bilgileri ve özel teklifleri almak için bültenimize abone olun.
                  </p>
                  <form>
                    <input className="w-100 mb-2" type="email" placeholder="E-posta adresinizi girin" required />
                    <button className="w-100" type="submit">Abone ol</button>
                  </form>
                </div>
              </div>
            </div>          
          </div>
          <div className="footer-bottom">
            <div className="row">
              <div className="col-6 d-flex align-items-center">
                <p className=" mb-0">© 2025 Bonero - Tüm hakları saklıdır | Bu web sitesi Group LTD tarafından geliştirilmiştir.</p>
              </div>
              <div className="col-4 d-flex align-items-center">
                <a className="footer-bottom-link me-3" href="#">Gizlilik Politikası</a>
                <a className="footer-bottom-link" href="#">Kullanım Şartları</a>
              </div>
              <div className="col-2 d-flex align-items-center justify-content-end">
                <div className="d-flex gap-3">
                  <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="social-icon-sm">
                    <SlSocialFacebook />
                  </a>
                  <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="social-icon-sm">
                    <FaInstagram />
                  </a>
                  <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" className="social-icon-sm">
                    <CiTwitter />
                  </a>            
                  <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="social-icon-sm">
                    <FaLinkedinIn />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </footer>
        <Script id="sticky2" strategy="afterInteractive">
        {`
          const nav = document.querySelector(".bonero-navbar");
          const navlinks = document.querySelectorAll(".nav-link");
          const bonero1 = document.querySelector(".bonero1");
          const bonero2 = document.querySelector(".bonero2");
          const btn = document.querySelector(".btn");

          if(nav){
            document.addEventListener("scroll", function(){
              if (window.scrollY > 150){
                nav.classList.add('my-navbar-bg');
                bonero1.classList.add('bonero1-display');
                bonero2.classList.add('bonero2-remove');
                btn.classList.add('btn-success');
                btn.classList.remove('blur');

                navlinks.forEach(link => {
                  link.classList.add('nav-link-change');
                });

              } else {
                nav.classList.remove('my-navbar-bg');
                bonero1.classList.remove('bonero1-display');
                bonero2.classList.remove('bonero2-remove');
                btn.classList.remove('btn-success');
                btn.classList.add('blur');

                navlinks.forEach(link => {
                  link.classList.remove('nav-link-change');
                });
              }
            });
          }
        `}
        </Script>
        <BootstrapClient/>
        </body>
    </html>
  );
}